### ISSUE TITLE
error on "type" property

### ISSUE THREAD

**Issue by ksevil** [toomuchdesign/openapi-ts-json-schema#211]
Hi,
First of all, thank you for this beautiful library.

I am using 
```
"openapi-ts-json-schema": "^0.9.1",
```

Have schema in typescript like below:

```
const FooSchema = {
  type: "object",
  properties: {
    type: { const: "FOO" },
    bar: { type: "string" },
  },
  required: ["type", "bar"],
} as const;

```

FooSchema has 2 properties,  ```type``` and ```bar```.

Equivalent schema in yaml:

```
type: object
properties:
  type:
    const: FOO
  bar:
    type: string
required:
  - type
  - bar
```

When i try to convert this schema to typescript, i am getting following error:
```
InvalidTypeError: Type {"const":"FOO"} is not a valid type
    at validateType (node_modules/@openapi-contrib/openapi-schema-to-json-schema/src/lib/converters/schema.ts:115:11)
```

It seems that ```type``` is recognized as a ```type``` of a schema but it is a name of the property.
